language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install nginx; fi
install:
  - curl -sSL http://nginx.org/download/nginx-1.8.0.tar.gz | tar zxfv - -C /tmp && cd /tmp/nginx-1.8.0/
  - ./configure --prefix=$HOME/nginxinstall --with-http_ssl_module
  - make
  - make install
  - export PATH="$PATH:$HOME/nginxinstall/sbin/"
  - cd $OLDPWD
before_script:
  - npm install -g bower
  - npm install -g gulp
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh --quiet verify
notifications:
  webhooks:
    secure: "VASW9+87Yl4roIDDw/+4DZYCIqAzdATEk4w52TIWDdG1mmqV1Z83Iol2sQdAViUctXzxIto/OibCGzBlsUFp8J+J6Yw+BOng4jrOTbFMguQw+/UMhRmtLIMu/eWJMiFr7Homjan5owu1TZmfIkR8XYxXyeY4ITJqJkkDmq53eHE="
  on_success: always
  on_failure: always
  on_start: always
env:
  - KOREBUILD_TEST_SKIPMONO=1  